// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBod8AnSxtXfBcTt3sd9SMnQi4TXQqdVB8',
    appId: '1:320162145263:web:db35b667eff1c2fb8b8c1a',
    messagingSenderId: '320162145263',
    projectId: 'job-timer-99a48',
    authDomain: 'job-timer-99a48.firebaseapp.com',
    storageBucket: 'job-timer-99a48.appspot.com',
    measurementId: 'G-JJSZJV1BRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZ9GUVfULSaVlhRTYSxWeyMb2RuemiFU',
    appId: '1:320162145263:android:e9dc24a8d9b5df788b8c1a',
    messagingSenderId: '320162145263',
    projectId: 'job-timer-99a48',
    storageBucket: 'job-timer-99a48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jzKP5Ztalp24mgiX9gjeIGGGY-_GaI8',
    appId: '1:320162145263:ios:4e33b13cfda2d2de8b8c1a',
    messagingSenderId: '320162145263',
    projectId: 'job-timer-99a48',
    storageBucket: 'job-timer-99a48.appspot.com',
    iosClientId: '320162145263-qfudmhd1noum6oeun748al15uqfq6fre.apps.googleusercontent.com',
    iosBundleId: 'com.br.innovation.jobTimer',
  );
}
